### PR TITLE
Make ruby_ship possible on FreeBSD platform. Tested with: FreeBSD 10.…

### PR DESCRIPTION
**Pull request by olevole**
…2, FreeBSD 11-head and Ruby 2.2.3

### CODE REVIEW

**Comment by stephan-nordnes-eriksen** [comment]
Nice! I don't have any machines running freebsd, so I will just assume this works :)

Thanks!

**Comment by olevole** [comment]
I've tested this in my labs before pull request. Work like a charm ;)
~~~
% uname -a
FreeBSD jail1.my.domain 11.0-CURRENT FreeBSD 11.0-CURRENT #12 r288145M: Wed Sep 23 21:13:01 UTC 2015     root@home.my.domain:/usr/jails/src/obj_amd64_amd64_11/usr/src/sys/GENERIC.CBSD  amd64

% ./tools/ruby_ship_build.sh /usr/ports/distfiles/ruby/ruby-2.2.3.tar.xz
   ...
Ruby Ship finished installing Ruby 2.2.3!
Run scripts by using the bin/ruby_ship.sh as you would use the normal ruby command.
Eg.: bin/ruby_ship.sh -v
=> ruby 2.2.3...

% file -s bin/shipyard/freebsd_ruby/bin/ruby
bin/shipyard/freebsd_ruby/bin/ruby: ELF 64-bit LSB shared object, x86-64, version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 11.0 (1100077), not stripped

% bin/ruby_ship.sh -e "puts 'Ruby Ship works!'"
Ruby Ship works!
~~~

Thanks for nice stuff! WBR,

**Comment by stephan-nordnes-eriksen** [comment]
Could you try to run the implementation test also?

`bin/ruby_ship.sh tools/implementation_tests.rb`

**Comment by olevole** [comment]
Hmm, I need a little time to look at this in more detail:
~~~
% bin/ruby_ship.sh tools/implementation_tests.rb
Test success: 1
Test success: 2
Test success: 3
/root/ruby_ship/bin/shipyard/freebsd_ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler (LoadError)
        from /root/ruby_ship/bin/shipyard/freebsd_ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from tools/implementation_tests.rb:75:in `block in <main>'
        from tools/implementation_tests.rb:88:in `call'
        from tools/implementation_tests.rb:88:in `block in <main>'
        from tools/implementation_tests.rb:86:in `each'
        from tools/implementation_tests.rb:86:in `each_with_index'
        from tools/implementation_tests.rb:86:in `<main>'
~~~

**Comment by stephan-nordnes-eriksen** [comment]
Yep.. you need to install bundler.

A simple `bin/ruby_ship_gem.sh install bundler` should do. This does not come with every version of ruby, but most people use it, so I always pre-install it into the rubies.

**Comment by olevole** [comment]
Thanks, not looks better:

~~~
bin/ruby_ship_gem.sh install bundler
Fetching: bundler-1.10.6.gem (100%)
Successfully installed bundler-1.10.6
Parsing documentation for bundler-1.10.6
Installing ri documentation for bundler-1.10.6
Done installing documentation for bundler after 5 seconds
1 gem installed

%  bin/ruby_ship.sh tools/implementation_tests.rb
Test success: 1
Test success: 2
Test success: 3
Test success: 4
-----------RESULTS-----------
All tests succeeded. Ruby ship is ready to sail!
~~~

**Comment by stephan-nordnes-eriksen** [comment]
Great!

Mind adding the new files to the repo?

**Comment by stephan-nordnes-eriksen** [comment]
Looking at this now, it does not appear that you have included the actual ruby-runtime-files themselves into the repo.

Normally this would be a no-go, but the point of this repo is that it is "download-n-play". If you could add these in a separate PR that would be great.

**Comment by olevole** [comment]
I specifically did not commit ruby binary - as it build ELF executable for experimental version of FreeBSD. I'm not sure that build from FreeBSD 11 (development version FreeBSD) will be works on FreeBSD 8, for example. I play and test this case tomorrow and if all is well - create separated pull request for all changes.

**Comment by stephan-nordnes-eriksen** [comment]
I see.. I know too little about FreeBSD to make an informed decision. Would be great if you make a PR if you see that it works in a non-beta version of FreeBSD.

At least the build tools now appear to work for all freebsd. Thanks for the help!

**Pull request merged**
