### PR TITLE
fix error with heroku CLI

### PR DESCRIPTION
**Pull request by eadmaster**
gives unexpected argument "-I"

https://devcenter.heroku.com/articles/heroku-command-line

### CODE REVIEW

**Comment by stephan-nordnes-eriksen** [comment]
Does the other platforms have the same issue?

**Comment by stephan-nordnes-eriksen** [comment]
And also: thanks for the PR

**Comment by eadmaster** [comment]
I haven't tested, but i guess it would be a good idea to change them as well...

**Comment by stephan-nordnes-eriksen** [comment]
Sorry for taking so long on this PR. I am trying to figure out why it was designed like this originally as I faintly remember having some kinds of problems which caused me select the ordering which is currently in master. I will get to the bottom of it as soon as possible.

**Comment by stephan-nordnes-eriksen** [comment]
I have looked into this now and this PR looks good, but I have also gone into the build scripts and fixed this, and some other issues, in my latest commits. I have pushed new wrappers for darwin, but not linux.

Maybe you could run `./tools/ruby_ship_build.sh /Users/stephan/Downloads/ruby-2.3.1.tar.gz` and do a PR with all the fixed wrappers and even the new binaries for linux? That would be much appreciated!

**Pull request merged**
